### ISSUE TITLE
first test on BleskOS

### ISSUE THREAD

**Issue by davidgaosheng** [VendelinSlezak/BleskOS#17]
I tested BleskOS on my real computer. results: usb mouse was found and listed in Connected Hardware, and can be used to draw something by Graphic Editor; usb keyboard was not found and not listed in Connected Hardware.  The real computer is a Asus server, built nearly 10 years ago, with 2 CPU packages, 4 cores in each package.

**Comment by VendelinSlezak** [comment]
Thank you for testing BleskOS on real computer!
First thing that comes to my mind is that you maybe have computer that have some UHCI/OHCI ports and some xHCI ports. I encountered such computer too. BleskOS currently do not have driver for xHCI, so it is not able to recognize USB keyboard in such port. So as first thing, I would try to insert USB keyboard to all ports. BleskOS should recognize keyboard up to one second.
Anyway, we need to get more info about hardware that is in System log. Also if communicating with USB keyboard failed somehow, we will see report of what happened here. In update 2 you can open system log by mouse(Main window>System board>click on [L] Open system log, you can close system log by clicking again). You can scroll down by mouse wheel. So please post some photos what BleskOS prints here.

**Comment by davidgaosheng** [comment]
![log1](https://github.com/VendelinSlezak/BleskOS/assets/78395860/05b33897-6662-47b7-b094-9ae420810930)
![log2](https://github.com/VendelinSlezak/BleskOS/assets/78395860/ffecc43b-5f2a-4abd-8cca-0b2a1d0d59e5)
![log3](https://github.com/VendelinSlezak/BleskOS/assets/78395860/e3ce03f0-6402-4190-b264-a5d05754a38e)
![log4](https://github.com/VendelinSlezak/BleskOS/assets/78395860/deb55aae-930d-40bf-9b58-d23dd47d4481)
![log5](https://github.com/VendelinSlezak/BleskOS/assets/78395860/fca3acbe-d5c3-4de5-9f3a-44f980a25d8e)
![log6](https://github.com/VendelinSlezak/BleskOS/assets/78395860/a995dff7-8c5f-4ec5-856b-48beec44f5f0)

**Comment by davidgaosheng** [comment]
sudo dd if=bleskos_2023_update_2.img of=/dev/sdb, burn the img into a usbdisk, boot the server computer with the usbdisk. there are 1 usb keybord, 1 ps/2 keyboard, 2 usb mouse. both the usb mouse and the usb keyboard work in legacy mode. after boot, usb keyboard lost its function while the usb mouse works. so i had to use the ps/2 keyboard to strike "L" to show the logs.

**Comment by VendelinSlezak** [comment]
Thank you for your time for posting log. It looks like there is not enough time for setting address. At afternoon when I will went home, I will increase this time and add more logging. Hopefully it will help.

**Comment by VendelinSlezak** [comment]
You can try update 3. I improve UHCI driver, so we will see if that helps. If not, please post what will be logged in System log. BTW You can open System log without keyboard, just with mouse and you can also scroll down by mouse wheel.

**Comment by davidgaosheng** [comment]
![p1](https://github.com/VendelinSlezak/BleskOS/assets/78395860/85b038ac-e637-4ea9-bc3e-79284983a80f)
![p2](https://github.com/VendelinSlezak/BleskOS/assets/78395860/164479ae-01bf-4df6-bf19-a08418b5abb5)
![p3](https://github.com/VendelinSlezak/BleskOS/assets/78395860/994a004b-a2b6-4feb-93e3-01e49ea213a9)
![p4](https://github.com/VendelinSlezak/BleskOS/assets/78395860/ebfde193-2efc-41d2-95d5-54e9efd62534)

**Comment by VendelinSlezak** [comment]
So this shows that problem occurs during reading full USB descriptor. Please can you try this image? It skips reading USB descriptor on UHCI and goes right on setting address. If it will not work, please post what System log says.
[bleskos_2023_update_4_not_reading_uhci_descriptor.img.zip](https://github.com/VendelinSlezak/BleskOS/files/12795237/bleskos_2023_update_4_not_reading_uhci_descriptor.img.zip)

**Comment by davidgaosheng** [comment]
![log](https://github.com/VendelinSlezak/BleskOS/assets/78395860/f45688b4-35c2-4a88-aef4-dff05b0cbadf)
Great! now both keyboard and mouse works well. Plug & Play works well too. BTW are they interrupt driven or polling driven? I mean do host controller send interrupts to system CPU when it receives keyboard and mouse input?

**Comment by VendelinSlezak** [comment]
I am glad to hear that. I think I founded bug. In fact, it was happening to my USB keyboard also, but it did not result into block of it. Problem was that reading USB descriptor from low-speed device takes 5 packets, but I was waiting only to 3 packets to be transferred. So your keyboard did not send whole descriptor and BleskOS was already requesting setting of address, what caused this error. Solution was just to change that one incorrect number in code to wait for all 5 packets to be transferred. It should be working in update 5. Can you please test it to confirm if it solved this issue?

**Comment by davidgaosheng** [comment]
hello!
Usb keyboard and mouse in BleskOS update6 works very well on my Asus Server.

**Comment by VendelinSlezak** [comment]
Nice. Then I am closing this issue.
