### ISSUE TITLE
Keyboard/Mouse dosn't work after boot

### ISSUE THREAD

**Issue by KingVentrix007** [VendelinSlezak/BleskOS#22]
**Environment**
Real hardware:
i3-4170 @ 3.70GHz
8192MB ram
No harddisk/optical disk
Booted from FAT32 formated USB(using rufus)

**Describe the bug**
I can select a boot option from the bleskOS bootloader, but as soon as it gets to the main menu it stops working, no keyboard or mouse input.

**System log**
Can't access it.

**Additional context**
As far as i know, the keyboard and mouse are both USB and the bios is not emulating PS/2(if it is i cant find anythig about it on the bios settings)
When it displays the Logo with the loading bar beneath it, it says starting PS/2 emulation(or something similer)

P.S, sorry for the poor spelling, I struggle with that.

**Comment by VendelinSlezak** [comment]
Do your computer have USB 3.0 ports?

**Comment by KingVentrix007** [comment]
According to the BIOS it does(USB3_NUMBER). The mouse and keyboard are both plugged into a usb 3 port

**Comment by VendelinSlezak** [comment]
Well, that explains this problem. BleskOS do not have driver for xHCI controller, what is only type of controller that is dealing with USB 3.0 ports. So unfortunately you cannot use USB devices on this computer now. However I am planning to write xHCI driver, but I cannot say exactly when, maybe in few months. Up until then, you can use only PS/2 devices, if you have some and if your computer have PS/2 port.

**Comment by KingVentrix007** [comment]
Ah okay, thank you.
