### ISSUE TITLE
BIG_ENDAIN in bleskos.h

### ISSUE THREAD

**Issue by defdefred** [VendelinSlezak/BleskOS#29]
Unfortunately, the "I" and the "A" are swapped to form the correct word in https://github.com/VendelinSlezak/BleskOS/blob/master/source/bleskos.h

https://en.wikipedia.org/wiki/Endianness

**Comment by defdefred** [comment]
Made a PR to fix endianess.
It is my first ever, so I may have made mistakes.

**Comment by VendelinSlezak** [comment]
Thank you for catching this, it is now fixed with your PR.
