### ISSUE TITLE
ODT file failed to open

### ISSUE THREAD

**Issue by defdefred** [VendelinSlezak/BleskOS#72]
**Environment**
qemu

**Describe the bug**
Opening "Free_Test_Data_100KB_ODT.odt" from the virtual disk.img provided via the last pull request, failed.
![odt_failed](https://github.com/VendelinSlezak/BleskOS/assets/17281367/b440f882-b7b8-4cd1-b102-691ead1206c4)

**System log**
[odt_failed.log.txt](https://github.com/VendelinSlezak/BleskOS/files/14324453/odt_failed.log.txt)

**Comment by VendelinSlezak** [comment]
There was little bug in DEFLATE decoder that in edge situation (as in this file) did not decode ending character, so it then messed up. It is fixed in update 18.
