### ISSUE TITLE
typedef trap

### ISSUE THREAD

**Issue by defdefred** [VendelinSlezak/BleskOS#80]
I found this:
```
$ grep typedef -R *
source/bleskos.h:typedef unsigned char byte_t;
source/bleskos.h:typedef unsigned short word_t;
source/bleskos.h:typedef unsigned int dword_t;
source/bleskos.h:typedef unsigned long qword_t;
```
But according to https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Primitive-Types
**int**: The 32-bit int data type can hold integer values in the range of -2,147,483,648 to 2,147,483,647. You may also refer to this data type as signed int or signed.
**unsigned int**: The 32-bit unsigned int data type can hold integer values in the range of 0 to 4,294,967,295. You may also refer to this data type simply as unsigned.

=> Always 32 bits

**long int**: The 32-bit long int data type can hold integer values in the range of at least -2,147,483,648 to 2,147,483,647. (Depending on your system, this data type might be 64-bit, in which case its range is identical to that of the long long int data type.) You may also refer to this data type as long, signed long int, or signed long.
**unsigned long int**: The 32-bit unsigned long int data type can hold integer values in the range of at least 0 to 4,294,967,295. (Depending on your system, this data type might be 64-bit, in which case its range is identical to that of the unsigned long long int data type.) You may also refer to this data type as unsigned long.

=> Also 32 bits for x86

**long long int**: The 64-bit long long int data type can hold integer values in the range of -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807. You may also refer to this data type as long long, signed long long int or signed long long. This type is not part of C89, but is both part of C99 and a GNU C extension.
**unsigned long long int**: The 64-bit unsigned long long int data type can hold integer values in the range of at least 0 to 18,446,744,073,709,551,615. You may also refer to this data type as unsigned long long. This type is not part of C89, but is both part of C99 and a GNU C extension. 

=> Always 64 bits

Other solution is to us <stdint.h> with type int32_t, uint32_t, int64_t, uint64_t, etc.

**Comment by VendelinSlezak** [comment]
I apologize, I am not exactly sure where is issue?

BTW One thing I noticed from this was that for qword_t I had "long" so I fixed it to "long long", and I also change "long" to "long long" in method for drawing ellipse that was producing weird shape, and now it works nicely

**Comment by defdefred** [comment]
Exactly, with long long qword_t is now really 4 x word :-)
